name: Build and Deployment

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun i
      - run: bun run build

  deployment:
    name: Deployment
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Connect SSH and Run Scripts
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm use 20
            export BUN_INSTALL="$HOME/.bun"
            export PATH=$BUN_INSTALL/bin:$PATH
            cd /root/projects/quick-dine-service
            git checkout .
            git pull
            bun i
            bun run prisma:setup
            pm2 restart quickdine-service
